GreenBankObservatory/dysh

- src/dysh/fits/sdfitsload.py
Fixed some errors in `SDFITSLoad`
> Fixed errors with summary method

- pyproject.toml
- src/dysh/fits/__init__.py
- src/dysh/shell.py
New version of #108 
Implementation of issue #106 
- Create a `$ dysh` entry point
- `$ dysh` will load an IPython shell, and preload several convenvience functions
- `$ dysh /path/to/sdfits1.fits /path/to/sdfits2.fits` will pre-load all given SDFITS paths into `sdfits_files` variable
> First draft of dysh shell

- src/dysh/spectra/tests/test_scan.py
Reverts GreenBankObservatory/dysh#121
This just removes the debug printouts that were accidentally merged
> Revert "Add some printouts to debug platform-dependent precision"

- src/dysh/coordinates/core.py
- src/dysh/spectra/core.py
- src/dysh/spectra/scan.py
- src/dysh/spectra/spectrum.py
here's some comments, which should close the review on 189.
Major thing: I computed nedge differently, as I understand the API, it was wrong before. 
See the @pjt symbols in the code.  All @pjt's should be removed upon acceptance or not.
> 189 review1

- src/dysh/fits/gbtfitsload.py
This fixes Issue #211 
Not elegant at all, but I'm dying to get summary marked as done.
> Fix bug reporting wrong number of integrations

- docs/source/for_beta_testers/beta_testing.rst
- docs/source/whatsnew/0.3.rst
Updates installation instructions and links for beta testing.
> Update beta docs

- src/dysh/coordinates/tests/test_coordinates_core.py
- src/dysh/spectra/tests/test_spectra_core.py
- src/dysh/util/core.py
Adds some basic unit tests and removes some unused functions.
> Q5 unit tests PS

- src/dysh/spectra/spectrum.py
- src/dysh/spectra/tests/test_spectrum.py
Fixes a bug that resulted in changing units for Spectrum objects
It also adds the `truediv` operation as mentioned in Issue #241.
> Spectrum arithmetic bug fixes

- docs/source/modules/dysh.fits.rst
- src/dysh/fits/gb20mfitsload.py
- src/dysh/fits/sdfitsload.py
- src/dysh/fits/tests/test_gb20mfitsload.py
- Fixes an error where `SDFITSLoad` would overwrite the `"OBSMODE"` column in its `_index`.
- Adds test for the `"OBSMODE"` column.
- Add documentation for `getps`.
> 20m index fix

- testdata/AGBT05B_047_01/gbtidl/README.md
Add: documentation on how the GBTIDL spectrum for AGBT05B_047_01 was produced.
> Solve issue #220

- src/dysh/fits/tests/test_gbtfitsload.py
- src/dysh/spectra/scan.py
Changes: 
- Where the user message about blanked integrations is issued.
- Adds more tests.
> 133 PS review

- notebooks/examples/metadata_management.ipynb
Just a very basic notebook showing how to use some of the new features.
> Adds example notebook showing how to use the metadata getter/setter

- docs/source/index.rst
- docs/source/whatsnew/index.rst
- notebooks/examples/index.rst
Here are some small changes. Otherwise the PR looks great!
> Cat docs devel mwp review

- src/dysh/fits/gbtfitsload.py
- src/dysh/fits/tests/test_gbtfitsload.py
This is an ugly fix for issue #256.
It adds updating the "RADESYS" column of the underlying `SDFITSLoad.index` objects in `GBTFITSLoad._sdf`.
> Issue 256 index update

- notebooks/examples/tests/test_notebooks.py
- pyproject.toml
- src/dysh/util/download.py
- src/dysh/util/tests/test_download.py
* Removes `glob2` as a dependency.
* Changes the use of `glob` to `Pathlib.path.glob`.
* Changes return of `from_url` when attempting to download an existing file.
* Adds test to `from_url` for downloading an existing file.
> Cat docs devel PS review

- src/dysh/shell/shell.py
This never made it into main, and now I'm not sure we could merge the original path cleanly due to the version change and the addition of the verbosity flag (`-v`). I opted for what I know: copy the code and create a new PR.
> Add: version flag for dysh cli

- src/dysh/fits/gbtfitsload.py
- src/dysh/spectra/scan.py
Fixed syntax on two log statements and added one additional debug statement
> Fix some log statements

- pyproject.toml
- src/dysh/spectra/tests/test_spectrum.py
I had to start a new branch because the other one had deleted part of Evan's work and merging main did not catch the difference.
> Fix: use line width error during test

- docs/source/whatsnew/0.4.rst
- docs/source/whatsnew/CHANGES.rst
- src/dysh/__init__.py
- src/dysh/util/gaincorrection.py
> Release 0.4.0

- docs/source/for_beta_testers/beta_testing.rst
- docs/source/getting_started/index.rst
- docs/source/whatsnew/0.4.rst
- docs/source/whatsnew/CHANGES.rst
- src/dysh/coordinates/core.py
- src/dysh/log.py
- src/dysh/spectra/spectrum.py
- src/dysh/spectra/tests/test_spectrum.py
- src/dysh/util/gaincorrection.py
Updates documentation for 0.4.2 beta testing, and some other fixes.
> Beta testing 0.4.2

- src/dysh/util/gaincorrection.py
- src/dysh/util/weatherforecast.py
This PR is a review for branch `441-implement-opacity-correction`.
It mainly contains fixes to the docstrings.
> 441 implement opacity correction PS review

- src/dysh/plot/tests/test_specplot.py
Fix: plot will not show when running test with a display
> specplot-test-fix

- src/dysh/spectra/scan.py
- src/dysh/util/gaincorrection.py
Fix: minor changes to docstrings and make zenith opacity optional for 'ta' scaling
> 489-implement-tasnu-scaling-factors-PS-review

- src/dysh/fits/gbtfitsload.py
- src/dysh/fits/tests/test_gbtfitsload.py
- Add a check that request scan numbers are actually in the file, if not raise a ValueError
- Add a test thereof
> fix for issue 462

- src/dysh/fits/gbtfitsload.py
- src/dysh/fits/sdfitsload.py
- src/dysh/fits/tests/test_gbtfitsload.py
Fill RADESYS for galactic coordinates, refactor code and adds test
> Fill RADESYS for galactic coordinates

- src/dysh/__init__.py
We should update the package version after every feature release, so we can keep track of what is being used for bug reports and communicating with users effectively.
> Bump package version to 0.4.3

- .gitignore
- src/dysh/fits/gbtfitsload.py
- src/dysh/spectra/scan.py
- testdata/AGBT18B_354_03/gbtidl_outputs/README.md
Minor fixes to docstrings and add the possibility of using `np.array` as `scan` input.
It also includes some old files I had not committed before, sorry to piggyback on this.
> 546 implement getsigref ps review

- src/dysh/plot/specplot.py
- src/dysh/spectra/spectrum.py
Fix for [issue 598](https://github.com/GreenBankObservatory/dysh/issues/598), as well as some extra functionality for unfreezing axes.
> 598 iplotter ylim

- src/dysh/fits/core.py
- src/dysh/fits/gbtfitsload.py
- src/dysh/fits/tests/test_gbtfitsload.py
This changes some doc strings, lets 'show' be any kind of Sequence, and fixes the failing test.
> Summary issues review mp

- src/dysh/fits/sdfitsload.py
- src/dysh/fits/tests/test_sdfitsload.py
fix: wrong reduction operation (issue #653 )
> Fix issue 653

- src/dysh/plot/specplot.py
Some minor changes to the code.
* Remove offset from color bar and add it to the label when necessary
* Use f-string justification to keep columns aligned
* Move the font selection to the base class so both children use the same font
> remove offset for ScanPlot and justify header columns

- README.md
- docs/source/getting_started/index.rst
Fix for issues #201 and #200, and README.md updates.
> Fix: issue #201
