.github/workflows/release.yml
"Build with hatch" step was missing a `run:` block
=> Fix syntax error in release.yaml

.readthedocs.yaml, docs/source/conf.py
Hope it works. In the end, I'd just forgotten to change the path to conf.py in .readthedocs.yaml, which is why they'd build locally but not when pushed.
=> Another merge to get the docs working

.readthedocs.yaml, docs/Makefile, requirements.txt
Changes to fix the bug reported in issue https://github.com/GreenBankObservatory/dysh/issues/90. It was mainly just fixing paths in the .readthedocs.yaml file. Requirements.txt file also had some dependency issues for Python 3.8 that I resolved. Docs now build with the same hatch environment. See https://dysh.readthedocs.io/en/cat-devel/for_developers/doc_standards.html for the new docs instructions.
=> clean up #90 bug fix

.github/workflows/hatch-and-pytest.yml, .github/workflows/pyinstaller.yml, pyproject.toml
A few minor tweaks to synchronize test matrix with supported Python versions. Python 3.8 is fully dropped, Python 3.12 is added
Note that these places need to change:
1. `pyproject.toml`:
- `[project.requires-python]`: Tells pip which versions of Python are allowed to install dysh
- `[tool.hatch.envs.test.matrix]`: Tells hatch which versions to use in its test matrix (for local tests only, at least currently)
- `[project.classifiers]`: Inform PyPI about trove classifiers (for search/metadata purposes)
2. `.github/workflows/{hatch-and-pytest,pyinstaller}.yaml:jobs.build.strategy.matrix.python-version`: Add to GH Actions build matrix
=> Drop support for Python 3.8; add support for Python 3.12

src/dysh/plot/specplot.py, src/dysh/spectra/scan.py
These were resulting in SyntaxWarning in Python 3.12:
```plain
dysh/src/dysh/plot/specplot.py:10: SyntaxWarning: invalid escape sequence '\*'
"""
dysh/src/dysh/plot/specplot.py:91: SyntaxWarning: invalid escape sequence '\*'
"""
dysh/src/dysh/plot/specplot.py:167: SyntaxWarning: invalid escape sequence '\*'
"""Set x and y labels according to spectral units
dysh/src/dysh/spectra/scan.py:155: SyntaxWarning: invalid escape sequence '\d'
"""Average all polarizations in all scans in this ScanBlock
dysh/src/dysh/spectra/scan.py:175: SyntaxWarning: invalid escape sequence '\d'
"""Average all times and polarizations in all scans this ScanBlock
dysh/src/dysh/spectra/scan.py:697: SyntaxWarning: invalid escape sequence '\d'
"""
```
=> Fix invalid escape sequences in docstrings

src/dysh/spectra/tests/test_scan.py
This is just to trigger a build on Windows, since I don't currently have access to a Windows host to test
=> Add some printouts to debug platform-dependent precision

pyproject.toml
`$ dysh` (`dysh.shell`) requires `ipython`, so it needs to be migrated from an optional to a "core" dependency
=> Make ipython a core dependency

pyproject.toml
In trying to run notebooks from a clean install, I ran into wget module not found,  so we need to move it to core.
=> wget is core dependency because our notebooks used it

src/dysh/shell.py, src/dysh/test_shell.py
Add some very basic unit tests to prove that dysh shell at least works without errors
=> Add unit tests for dysh shell

docs/source/examples/positionswitch.rst, docs/source/examples/subbeamnod.rst, docs/source/examples/totalpower.rst, docs/source/getting_started/tutorials/GBT/tutorial-positionswitch.rst, src/dysh/fits/gbtfitsload.py
This PR updates the examples to work with ScanBlocks. It is mainly changing from `ta.plot()` to `ta[0].plot()`.
It also changes the `GBTSDFITSLoader.summary` to print when using `show_index=False`.
=> Update docs for beta

docs/source/examples/positionswitch.rst, docs/source/examples/subbeamnod.rst, docs/source/examples/totalpower.rst, docs/source/getting_started/tutorials/GBT/tutorial-positionswitch.rst, src/dysh/fits/gbtfitsload.py
This patch fixes Issue #132.
Now `gettp` will skip the creation of a `TPScan` if the input selection results in zero rows.
=> Patches for `gettp`

.env.template, docs/source/for_developers/doc_standards.rst
Pedro pointed out that it's much easier to build the docs with hatch than with the `.env` file. I changed the instructions accordingly and deleted the `.env.template` file.
=> Change autobuild instructions to hatch

src/dysh/coordinates/core.py
The equation for the radio velocity definition was mistyped. This also caused a `UnitConversionError` when trying to use baseline subtraction.
=> Fixes velocity definitions

src/dysh/spectra/spectrum.py, src/dysh/spectra/tests/test_spectrum.py
Adds `__rmul__`, `__radd__` and `__rsub__` operations for `Spectrum` objects and tests.
This should fix issue #243.
=> Fix: adds support for right hand side arithmetic operations on Spectrum

notebooks/examples/dataIO.ipynb, src/dysh/fits/gbtfitsload.py, src/dysh/fits/tests/test_gbtfitsload.py
- Minor changes to the `dataIO` example notebook (mostly adding spaces and removing a duplicate word).
- Fixes bug that would cause writing with `multifile=True` (with `len(fi)>1`) to always end in the same directory as where the call was made.
- Adds a test for writing the same file that was loaded.
- Adds teardown for tests that write files.
=> 270 psalas review

src/dysh/coordinates/core.py, src/dysh/spectra/spectrum.py, src/dysh/spectra/tests/test_spectrum.py
This fix forces the use of a spectral WCS object when creating a Spectrum, thus removing the error where Spectrum1D did not know how to handle celestial WCS coordinates. This also removes the STOKES axis from the WCS.
This would help fix #258 and #248 -- only in channel space. To make this work with velocity units we could add a unit conversion between frequency and velocity if needed (e.g., the user slices using velocity units on a `Spectrum` with `spectral_axis` in frequency units.
The unit tests showed no issues, but that may not be complete.
In draft status to see if the implementation makes sense to the development team.
=> Fix: slicing of Spectrum objects

src/dysh/__init__.py, src/dysh/shell/shell.py
Fix for #296 
Previous behavior:
```sh
$ dysh --version
8.7.12
```
New behavior:
```sh
$ dysh --version
0.3.0
```
=> dysh shell now handles --version flag

notebooks/examples/dataIO.ipynb, notebooks/examples/frequencyswitch.ipynb, notebooks/examples/metadata_management.ipynb, notebooks/examples/positionswitch.ipynb, notebooks/examples/smoothing.ipynb, notebooks/examples/subbeamnod.ipynb, notebooks/examples/tests/test_notebooks.py, notebooks/examples/velocity_frames.ipynb, pyproject.toml, requirements.txt, src/dysh/util/download.py
This PR is to add unit tests to `cat-docs-devel`, which is currently under review to merge into `main`. These tests are in `notebooks/examples/tests/test_notebook.py`
- `test_notebooks_execution()`: Tests that the notebooks in `notebooks/examples/` run without errors
- `test_single_top_level_header()`: Tests that the notebooks in `notebooks/examples/` each contain exactly one top-level header. Fixes issue identified in https://github.com/GreenBankObservatory/dysh/issues/334
There are a few other changes:
- The notebooks now use `pathlib.Path()` objects for all paths to prevent issues where GitHub actions could not find files
- `dataIO.ipynb` has a temporary fix to allow tests to pass despite https://github.com/GreenBankObservatory/dysh/issues/339
- Adds `nbformat`, `nbclient`, and `glob2` …
=> Add unit tests to documentation PR

src/dysh/fits/tests/test_sdfitsload.py
* Adds more comparisons to make sure `getspec` is retrieving the correct row from an SDFITS.
=> Add: additional sanity checks for getspec

src/dysh/spectra/spectrum.py, src/dysh/spectra/tests/test_spectrum.py
In this PR:
* Refactor the code for `Spectrum.smooth`. Not it is split into smoothing and decimation. This also adds a `Spectrum.decimate` method.
* Updates the WCS of a `Spectrum` after smoothing/decimating.
* Updates the value of `Spectrum._resolution`.
* Adds tests for `Spectrum.smooth`.
=> 307 wcs wrong after a smoothed spectrum is indexed ps review

src/dysh/fits/gbtfitsload.py
Found a few invalid log statements (via regex `\Wlogger\..*\(".*",`)
=> Fix all(?) remaining invalid print->logger conversions

src/dysh/spectra/spectrum.py, src/dysh/spectra/tests/test_spectrum.py
This PR changes the behavior of `Spectrum.shift` and `Spectrum.align_to` to return a new `Spectrum`.
=> Change: align_to and shift now return a copy

src/dysh/fits/gbtfitsload.py, src/dysh/fits/sdfitsload.py, src/dysh/fits/tests/test_gbtfitsload.py, src/dysh/spectra/scan.py, src/dysh/util/core.py, src/dysh/util/selection.py
The fix for this issue was not as simple as initially thought.  While the `setmask` argument was indeed missing from GBTFITSLoad.getspec/rawspectrum/rawspectra, there was a deeper issue that completely flagged rows were not removed in calibration routines (before create of relevant Scan class).   The fix for this necessitated a few other changes in selection.py having to do with how rules are constructed and compared. 
* add setmask argument to `GBTFITSLoad.xxspecxx`
* add `eliminate_flagged_rows` method to util.core
* ensure rows with all channels flagged are eliminated during calibration routines by calling the above
* add timestamp value to `util.core.generate_tag` to ensure tags are always unique
* ensure flagged channels are correctly represented in Flag selection rules (DataFrames) …
=> 442 flags not getting applied to calibration routine

src/dysh/log.py
This replaces_testcapi calls with a different call, but leaves the wrapper traceback munging problem for another issue (see comments in the issue #459).
=> remove _testcapi module, as it is not available in all OS/python versions

src/dysh/plot/specplot.py
Fixes [issue 536](https://github.com/GreenBankObservatory/dysh/issues/536), by making the default figure size (10,6) inches.
Other adjustments:
- monospace font
- second column shifted slightly to the left for readability
- velo entry has km/s unit removed (for space/readability)
=> Header adjustments

notebooks/developer/test_online.py, src/dysh/fits/gbtfitsload.py, src/dysh/fits/tests/test_gb20mfitsload.py, src/dysh/fits/tests/test_gbtfitsload.py, src/dysh/fits/tests/test_sdfitsload.py, src/dysh/util/files.py, src/dysh/util/tests/test_files.py
Ensured the .filename attribute is now populated when it was not.
=> 354 sdfitsload does not print the filepath

src/dysh/plot/specplot.py, src/dysh/spectra/spectrum.py
Another take at interactive selection.
```Python
%matplotlib ipympl # if needed
from dysh.spectra import Spectrum
s = Spectrum.fake_spectrum()
s.plot()
s.baseline(1, exclude=s.get_selected_regions())
```
=> Another option for interactive region selection

src/dysh/__init__.py, src/dysh/coordinates/core.py, src/dysh/plot/specplot.py, src/dysh/plot/tests/test_specplot.py, src/dysh/spectra/core.py, src/dysh/spectra/spectrum.py, src/dysh/spectra/tests/test_spectrum.py
This PR:
* Adds buttons and key strokes to delete one or all regions. You can delete all regions with `D` and a single region with `d` -- Issue #571 . 
* Add support for units in `Spectrum.get_selected_region()` -- Issue #572 .
* Fix issue #532 .
=> Specplot selection update

src/dysh/fits/gbtfitsload.py, src/dysh/util/core.py
Split summary into two functions summary and get_summary. get_summary does the heavy lifting of creating the DataFrame. summary now calls get_summary and displays the result using dysh.util.core.show_DataFrame. This will show the summary even if the call is not the last one in a cell.
It also adds an argument for the maximum number of rows and hides the index by default.
=> fix: issue #649

docs/source/conf.py
fix: issue #613
Set execution timeout to no limit
The issue seems to have gone away in the latest build of RtD. Can it hurt to add this?
=> Fix issue 613

src/dysh/spectra/spectrum.py, src/dysh/spectra/tests/test_spectrum.py
fix: issue #360 spectrum slicing order
It should now be possible to slice using negative values, or quantities in any order. If the start is negative, it will be cast into a positive value (astropy issue). If the start and stop are not negative, they will be sorted before slicing the underlying objects.
=> Issue #360

src/dysh/plot/specplot.py
Fix for issue #734 
It checks if another widget is enabled, and if so, does nothing with the selected regions.
=> Fix issue #734
